name: Ubuntu RDP

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-venv python3-pip xrdp unzip wget

    - name: Upgrade pip
      run: python3 -m pip install --upgrade pip wheel setuptools

    - name: Install requirements (skip uvloop)
      run: |
        if [ -f requirements.txt ]; then
          grep -v uvloop requirements.txt | xargs -n 1 pip install
        fi

    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -O ngrok.zip

    - name: Extract ngrok
      run: unzip ngrok.zip -d ngrok

    - name: Authenticate ngrok
      run: ./ngrok/ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Configure RDP user
      run: |
        sudo useradd -m runneradmin || true
        echo "runneradmin:@cyb3rking" | sudo chpasswd

    - name: Enable and start xrdp
      run: |
        sudo systemctl enable xrdp
        sudo systemctl start xrdp

    - name: Start ngrok tunnel (block job)
      run: ./ngrok/ngrok tcp 3389
